FROM grafana/grafana

#RUN grafana-cli plugins install redis-app
#RUN sudo systemctl restart grafana-server

ADD ./config.ini /etc/grafana/config.ini
#ADD ./provisioning/datasources/redistimeseries.yaml /etc/grafana/provisioning/datasources/redistimeseries.yaml
